=== L2jOrg/L2jOrg/dist/gameserver/data/spawn/spawn.dtd
<?xml version='1.0' encoding='utf-8'?>
<!ELEMENT list (spawn|territory)*>
<!ELEMENT spawn (territory|npc|point|rectangle|circle)*>
<!ATTLIST spawn
	name CDATA #IMPLIED
	group CDATA #IMPLIED
	respawn CDATA #IMPLIED
	count CDATA #IMPLIED
	respawn_random CDATA #IMPLIED
	respawn_pattern CDATA #IMPLIED
	period_of_day CDATA #IMPLIED>
<!ELEMENT territory (banned_territory|add)*>
<!ATTLIST territory
	name CDATA #IMPLIED>
<!ELEMENT banned_territory (add)*>
<!ELEMENT add (#PCDATA)>
<!ATTLIST add
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	zmin CDATA #REQUIRED
	zmax CDATA #REQUIRED>
<!ELEMENT npc (set|minions)*>
<!ATTLIST npc
	id CDATA #REQUIRED
	max CDATA #IMPLIED
	ai CDATA #IMPLIED>
<!ELEMENT set (#PCDATA)>
<!ATTLIST set
	name CDATA #REQUIRED
	value CDATA #REQUIRED>
<!ELEMENT minions (minion)*>
<!ELEMENT minion (#PCDATA)>
<!ATTLIST minion
	npc_id CDATA #REQUIRED
	ai CDATA #IMPLIED
	count CDATA #REQUIRED
	respawn CDATA #IMPLIED>
<!ELEMENT point (#PCDATA)>
<!ATTLIST point
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	z CDATA #REQUIRED
	h CDATA #IMPLIED>
<!ELEMENT rectangle (#PCDATA)>
<!ATTLIST rectangle
	x1 CDATA #REQUIRED
	y1 CDATA #REQUIRED
	x2 CDATA #REQUIRED
	y2 CDATA #REQUIRED
	zmin CDATA #REQUIRED
	zmax CDATA #REQUIRED>
<!ELEMENT circle (#PCDATA)>
<!ATTLIST circle
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	zmin CDATA #REQUIRED
	zmax CDATA #REQUIRED
	radius CDATA #REQUIRED>

=== L2jOrg/L2jOrg/dist/gameserver/data/spawn/17_10.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE list SYSTEM "spawn.dtd">

<list>
	<spawn group="olympiad_147_buffers" count="1" respawn="0" respawn_random="0" period_of_day="none">
		<point x="-89368" y="-252840" z="-3340" h="0"/>
		<npc id="36402"/>
	</spawn>
	<spawn group="olympiad_147_buffers" count="1" respawn="0" respawn_random="0" period_of_day="none">
		<point x="-86792" y="-252840" z="-3340" h="0"/>
		<npc id="36402"/>
	</spawn>
	<spawn group="olympiad_148_buffers" count="1" respawn="0" respawn_random="0" period_of_day="none">
		<point x="-76728" y="-252456" z="-7741" h="0"/>
		<npc id="36402"/>
	</spawn>
	<spawn group="olympiad_148_buffers" count="1" respawn="0" respawn_random="0" period_of_day="none">
		<point x="-74200" y="-252456" z="-7741" h="0"/>
		<npc id="36402"/>
	</spawn>
	<spawn group="olympiad_149_buffers" count="1" respawn="0" respawn_random="0" period_of_day="none">
		<point x="-89176" y="-239352" z="-8474" h="0"/>
		<npc id="36402"/>
	</spawn>
	<spawn group="olympiad_149_buffers" count="1" respawn="0" respawn_random="0" period_of_day="none">
		<point x="-87000" y="-239352" z="-8474" h="0"/>
		<npc id="36402"/>
	</spawn>
	<spawn group="olympiad_150_buffers" count="1" respawn="0" respawn_random="0" period_of_day="none">
		<point x="-76632" y="-239176" z="-8218" h="0"/>
		<npc id="36402"/>
	</spawn>
	<spawn group="olympiad_150_buffers" count="1" respawn="0" respawn_random="0" period_of_day="none">
		<point x="-74280" y="-239176" z="-8218" h="0"/>
		<npc id="36402"/>
	</spawn>
</list>
