=== L2jOrg/L2jOrg/Datapack/gameserver/data/items/items.xsd
<?xml version="1.1" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://l2j.org"
           xmlns="http://l2j.org"
           elementFormDefault="qualified">

    <xs:include schemaLocation="../xsd/common.xsd"/>

    <xs:element name="list">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="itemGroup" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="Weapon">
        <xs:complexContent>
            <xs:extension base="AbstractItem">
                <xs:sequence>
                    <xs:element name="attributes" type="WeaponAttributes"/>
                    <xs:element name="crystal" type="ItemCrystal"/>
                    <xs:element name="damage" type="WeaponDamage" minOccurs="0"/>
                    <xs:element name="stats" minOccurs="0" type="ItemStats"/>
                    <xs:element name="skills" minOccurs="0" type="ItemSkillsType"/>
                </xs:sequence>
                <xs:attribute name="type" type="WeaponType" use="required"/>
                <xs:attribute name="body-part" type="WeaponBodyPart"/>
                <xs:attribute name="magic" type="xs:boolean" default="false"/>
                <xs:attribute name="mana-consume" type="xs:int" default="0"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="WeaponAttributes">
        <xs:complexContent>
            <xs:extension base="Attributes">
                <xs:attribute name="enchant-enabled" type="xs:boolean" default="true"/>
                <xs:attribute name="commission-type" type="CommissionType" default="OTHER_WEAPON"/>
                <xs:attribute name="change-weapon" type="xs:int" default="0"/>
                <xs:attribute name="can-attack" type="xs:boolean" default="true"/>
                <xs:attribute name="restrict-skills" type="xs:boolean" default="false"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="WeaponDamage">
        <xs:attribute name="radius" type="xs:int"/>
        <xs:attribute name="angle" type="xs:int"/>
    </xs:complexType>

    <xs:complexType name="Armor">
        <xs:complexContent>
            <xs:extension base="AbstractItem">
                <xs:sequence>
                    <xs:element name="attributes" type="ArmorAttributes"/>
                    <xs:element name="crystal" type="ItemCrystal"/>
                    <xs:element name="stats" minOccurs="0" type="ItemStats"/>
                    <xs:element name="skills" minOccurs="0" type="ItemSkillsType"/>
                </xs:sequence>
                <xs:attribute name="type" type="ArmorType" use="required"/>
                <xs:attribute name="body-part" type="ArmorBodyPart" use="required"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="ArmorAttributes">
        <xs:complexContent>
            <xs:extension base="Attributes">
                <xs:attribute name="enchant-enabled" type="xs:boolean" default="true"/>
                <xs:attribute name="commission-type" type="CommissionType" default="OTHER_ITEM"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="Item">
        <xs:complexContent>
            <xs:extension base="AbstractItem">
                <xs:sequence>
                    <xs:element name="attributes" type="ItemAttributes"/>
                    <xs:element name="crystal" type="ItemCrystal" minOccurs="0"/>
                    <xs:choice minOccurs="0">
                        <xs:element name="action" type="ItemAction"/>
                        <xs:element name="extract" type="ItemExtract"/>
                        <xs:element name="skill-reducer" type="SkillReducer"/>
                        <xs:element name="transformation-book" type="TransformationBook"/>
                    </xs:choice>
                </xs:sequence>
                <xs:attribute name="type" type="EtcItemType" use="required"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="ItemAttributes">
        <xs:complexContent>
            <xs:extension base="Attributes">
                <xs:attribute name="immediate-effect" type="xs:boolean" default="false"/>
                <xs:attribute name="ex-immediate-effect" type="xs:boolean" default="false"/>
                <xs:attribute name="quest-item" type="xs:boolean" default="false"/>
                <xs:attribute name="self-resurrection" type="xs:boolean" default="false"/>
                <xs:attribute name="infinite" type="xs:boolean" default="false"/>
                <xs:attribute name="commission-type" type="CommissionType" default="OTHER_ITEM"/>
                <xs:attribute name="action" type="ActionType" default="NONE"/>
                <xs:attribute name="auto-use" type="AutoUseType" default="NONE"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:simpleType name="AutoUseType">
        <xs:restriction base="xs:token">
            <xs:enumeration value="NONE"/>
            <xs:enumeration value="SUPPLY"/>
            <xs:enumeration value="HEALING"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="AbstractItem" abstract="true">
        <xs:sequence>
            <xs:element name="restriction" type="Restriction"/>
            <xs:element name="condition" minOccurs="0" type="ItemUseCondition"/>
        </xs:sequence>
        <xs:attribute name="id" use="required" type="xs:positiveInteger"/>
        <xs:attribute name="name" type="xs:normalizedString" use="required"/>
        <xs:attribute name="icon" type="xs:token"/>
        <xs:attribute name="display-id" type="xs:int"/>
    </xs:complexType>

    <xs:complexType name="Restriction">
        <xs:attribute name="stackable" type="xs:boolean" default="false"/>
        <xs:attribute name="sellable" type="xs:boolean" default="true"/>
        <xs:attribute name="private-sellable" type="xs:boolean" default="true"/>
        <xs:attribute name="dropable" type="xs:boolean" default="true"/>
        <xs:attribute name="destroyable" type="xs:boolean" default="true"/>
        <xs:attribute name="tradable" type="xs:boolean" default="true"/>
        <xs:attribute name="depositable" type="xs:boolean" default="true"/>
        <xs:attribute name="clan-depositable" type="xs:boolean" default="true"/>
        <xs:attribute name="castle-depositable" type="xs:boolean" default="true"/>
        <xs:attribute name="freightable" type="xs:boolean" default="true"/>
        <xs:attribute name="commissionable" type="xs:boolean" default="true"/>
        <xs:attribute name="mailable" type="xs:boolean" default="true"/>
        <xs:attribute name="olympiad-restricted" type="xs:boolean" default="false"/>
        <xs:attribute name="hero" type="xs:boolean" default="false"/>
    </xs:complexType>

    <xs:complexType name="Attributes" abstract="true">
        <xs:attribute name="weight" type="xs:int" default="0"/>
        <xs:attribute name="price" type="xs:long" default="0"/>
        <xs:attribute name="duration" type="xs:long" default="-1"/>
        <xs:attribute name="reuse-delay" type="xs:long" />
        <xs:attribute name="for-npc" type="xs:boolean" default="false"/>
    </xs:complexType>

    <xs:complexType name="ItemCrystal">
        <xs:attribute name="type" type="CrystalType" default="NONE"/>
        <xs:attribute name="count" type="xs:int" default="0"/>
    </xs:complexType>

    <xs:complexType name="TransformationBook">
        <xs:attribute name="skill" type="xs:int" use="required"/>
    </xs:complexType>

    <xs:complexType name="SkillReducer">
        <xs:sequence>
            <xs:element name="skill" type="ItemSkillType" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="type" type="xs:token" default="ItemSkills"/>
    </xs:complexType>

    <xs:complexType name="ItemExtract">
        <xs:sequence>
            <xs:element name="item" type="ExtractableItem" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="max" type="xs:int" default="-1"/>
    </xs:complexType>

    <xs:complexType name="ItemAction">
        <xs:attribute name="handler">
            <xs:simpleType>
                <xs:restriction base="xs:token">
                    <xs:enumeration value="BeastSoulShot"/>
                    <xs:enumeration value="BeastSpiritShot"/>
                    <xs:enumeration value="BlessedSoulShots"/>
                    <xs:enumeration value="BlessedSpiritShot"/>
                    <xs:enumeration value="Book"/>
                    <xs:enumeration value="Bypass"/>
                    <xs:enumeration value="Calculator"/>
                    <xs:enumeration value="ChangeAttributeCrystal"/>
                    <xs:enumeration value="CharmOfCourage"/>
                    <xs:enumeration value="EnchantScrolls"/>
                    <xs:enumeration value="EventItem"/>
                    <xs:enumeration value="FatedSupportBox"/>
                    <xs:enumeration value="FishShots"/>
                    <xs:enumeration value="Harvester"/>
                    <xs:enumeration value="Maps"/>
                    <xs:enumeration value="MercTicket"/>
                    <xs:enumeration value="NicknameColor"/>
                    <xs:enumeration value="PetFood"/>
                    <xs:enumeration value="Recipes"/>
                    <xs:enumeration value="RollingDice"/>
                    <xs:enumeration value="Seed"/>
                    <xs:enumeration value="SoulShots"/>
                    <xs:enumeration value="SpecialXMas"/>
                    <xs:enumeration value="SpiritShot"/>
                    <xs:enumeration value="SummonItems"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>

    <xs:complexType name="ItemSkillsType">
        <xs:sequence>
            <xs:element name="skill" type="ItemSkillType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="ItemSkillType">
        <xs:attribute name="id" type="xs:positiveInteger" use="required"/>
        <xs:attribute name="level" type="xs:positiveInteger" default="1"/>
        <xs:attribute name="type" default="NORMAL">
            <xs:simpleType>
                <xs:restriction base="xs:token">
                    <xs:enumeration value="NORMAL"/>
                    <xs:enumeration value="ON_ENCHANT"/>
                    <xs:enumeration value="ON_EQUIP"/>
                    <xs:enumeration value="ON_UNEQUIP"/>
                    <xs:enumeration value="ON_CRITICAL_SKILL"/>
                    <xs:enumeration value="ON_MAGIC_SKILL"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="chance" type="xs:positiveInteger" default="100"/>
        <xs:attribute name="value" type="xs:int" default="0"/>
    </xs:complexType>

    <xs:complexType name="ExtractableItem">
        <xs:attribute name="id" type="xs:positiveInteger"/>
        <xs:attribute name="min-count" type="xs:positiveInteger" default="1"/>
        <xs:attribute name="max-count" type="xs:positiveInteger" default="1"/>
        <xs:attribute name="chance" type="xs:positiveInteger" default="100"/>
        <xs:attribute name="min-enchant" type="xs:nonNegativeInteger" default="0"/>
        <xs:attribute name="max-enchant" type="xs:nonNegativeInteger" default="0"/>
    </xs:complexType>

    <xs:complexType name="createItemType">
        <xs:attribute name="id" type="xs:positiveInteger"/>
        <xs:attribute name="count" type="xs:positiveInteger"/>
        <xs:attribute name="chance" type="xs:double"/>
    </xs:complexType>

    <xs:complexType name="playerType">
        <xs:attribute name="castle">
            <xs:simpleType>
                <xs:restriction base="xs:integer">
                    <xs:minInclusive value="-1"/>
                    <xs:maxInclusive value="9"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="hero" type="xs:boolean"/>
        <xs:attribute name="zone" type="xs:normalizedString"/>
        <xs:attribute name="level-min" type="xs:positiveInteger"/>
        <xs:attribute name="pledge-class">
            <xs:simpleType>
                <xs:restriction base="xs:int">
                    <xs:minInclusive value="-1"/>
                    <xs:maxInclusive value="11"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="level-max" type="xs:positiveInteger"/>
        <xs:attribute name="sex">
            <xs:simpleType>
                <xs:restriction base="xs:token">
                    <xs:enumeration value="FEMALE"/>
                    <xs:enumeration value="MALE"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="chaotic" type="xs:boolean"/>
        <xs:attribute name="flying" type="xs:boolean"/>
    </xs:complexType>

    <xs:complexType name="ItemUseCondition">
        <xs:choice maxOccurs="unbounded" minOccurs="0">
            <xs:element name="player" type="playerType"/>
        </xs:choice>
        <xs:attribute name="msg-id" type="xs:short" />
        <xs:attribute name="add-name" type="xs:boolean" />
        <xs:attribute name="msg" type="xs:string" />
    </xs:complexType>

    <xs:complexType name="ItemStats">
        <xs:sequence>
            <xs:element name="stat" type="ItemStat" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="ItemStat">
        <xs:attribute name="type" type="Stat"/>
        <xs:attribute name="value" type="xs:float"/>
    </xs:complexType>

    <xs:simpleType name="CommissionType">
        <xs:restriction base="xs:token">
            <xs:enumeration value="ONE_HAND_SWORD"/>
            <xs:enumeration value="ONE_HAND_MAGIC_SWORD"/>
            <xs:enumeration value="DAGGER"/>
            <xs:enumeration value="RAPIER"/>
            <xs:enumeration value="TWO_HAND_SWORD"/>
            <xs:enumeration value="ANCIENT_SWORD"/>
            <xs:enumeration value="DUALSWORD"/>
            <xs:enumeration value="DUAL_DAGGER"/>
            <xs:enumeration value="BLUNT_WEAPON"/>
            <xs:enumeration value="ONE_HAND_MAGIC_BLUNT_WEAPON"/>
            <xs:enumeration value="TWO_HAND_BLUNT_WEAPON"/>
            <xs:enumeration value="TWO_HAND_MAGIC_BLUNT_WEAPON"/>
            <xs:enumeration value="DUAL_BLUNT_WEAPON"/>
            <xs:enumeration value="BOW"/>
            <xs:enumeration value="CROSSBOW"/>
            <xs:enumeration value="FIST_WEAPON"/>
            <xs:enumeration value="SPEAR"/>
            <xs:enumeration value="OTHER_WEAPON"/>
            <xs:enumeration value="HELMET"/>
            <xs:enumeration value="ARMOR_TOP"/>
            <xs:enumeration value="ARMOR_PANTS"/>
            <xs:enumeration value="FULL_BODY"/>
            <xs:enumeration value="GLOVES"/>
            <xs:enumeration value="FEET"/>
            <xs:enumeration value="SHIELD"/>
            <xs:enumeration value="SIGIL"/>
            <xs:enumeration value="UNDERWEAR"/>
            <xs:enumeration value="CLOAK"/>
            <xs:enumeration value="RING"/>
            <xs:enumeration value="EARRING"/>
            <xs:enumeration value="NECKLACE"/>
            <xs:enumeration value="BELT"/>
            <xs:enumeration value="BRACELET"/>
            <xs:enumeration value="HAIR_ACCESSORY"/>
            <xs:enumeration value="POTION"/>
            <xs:enumeration value="SCROLL_ENCHANT_WEAPON"/>
            <xs:enumeration value="SCROLL_ENCHANT_ARMOR"/>
            <xs:enumeration value="SCROLL_OTHER"/>
            <xs:enumeration value="SOULSHOT"/>
            <xs:enumeration value="SPIRITSHOT"/>
            <xs:enumeration value="PET_EQUIPMENT"/>
            <xs:enumeration value="PET_SUPPLIES"/>
            <xs:enumeration value="CRYSTAL"/>
            <xs:enumeration value="RECIPE"/>
            <xs:enumeration value="MAJOR_CRAFTING_INGREDIENTS"/>
            <xs:enumeration value="LIFE_STONE"/>
            <xs:enumeration value="SOUL_CRYSTAL"/>
            <xs:enumeration value="ATTRIBUTE_STONE"/>
            <xs:enumeration value="WEAPON_ENCHANT_STONE"/>
            <xs:enumeration value="ARMOR_ENCHANT_STONE"/>
            <xs:enumeration value="SPELLBOOK"/>
            <xs:enumeration value="GEMSTONE"/>
            <xs:enumeration value="POUCH"/>
            <xs:enumeration value="PIN"/>
            <xs:enumeration value="MAGIC_RUNE_CLIP"/>
            <xs:enumeration value="MAGIC_ORNAMENT"/>
            <xs:enumeration value="DYES"/>
            <xs:enumeration value="OTHER_ITEM"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="itemGroup" type="AbstractItem" abstract="true" />
    <xs:element name="weapon" type="Weapon" substitutionGroup="itemGroup"/>
    <xs:element name="armor" type="Armor" substitutionGroup="itemGroup"/>
    <xs:element name="item" type="Item" substitutionGroup="itemGroup"/>

    <xs:simpleType name="ActionType">
        <xs:restriction base="xs:token">
            <xs:enumeration value="CALC"/>
            <xs:enumeration value="CALL_SKILL"/>
            <xs:enumeration value="CAPSULE"/>
            <xs:enumeration value="CREATE_MPCC"/>
            <xs:enumeration value="DICE"/>
            <xs:enumeration value="EQUIP"/>
            <xs:enumeration value="FISHINGSHOT"/>
            <xs:enumeration value="HARVEST"/>
            <xs:enumeration value="HIDE_NAME"/>
            <xs:enumeration value="KEEP_EXP"/>
            <xs:enumeration value="NICK_COLOR"/>
            <xs:enumeration value="NONE"/>
            <xs:enumeration value="PEEL"/>
            <xs:enumeration value="RECIPE"/>
            <xs:enumeration value="SEED"/>
            <xs:enumeration value="SHOW_ADVENTURER_GUIDE_BOOK"/>
            <xs:enumeration value="SHOW_HTML"/>
            <xs:enumeration value="SHOW_SSQ_STATUS"/>
            <xs:enumeration value="SKILL_MAINTAIN"/>
            <xs:enumeration value="SKILL_REDUCE"/>
            <xs:enumeration value="SOULSHOT"/>
            <xs:enumeration value="SPIRITSHOT"/>
            <xs:enumeration value="START_QUEST"/>
            <xs:enumeration value="SUMMON_SOULSHOT"/>
            <xs:enumeration value="SUMMON_SPIRITSHOT"/>
            <xs:enumeration value="XMAS_OPEN"/>
            <xs:enumeration value="SKILL_REDUCE_ON_SKILL_SUCCESS"/>
            <xs:enumeration value="SHOW_TUTORIAL"/>
        </xs:restriction>

    </xs:simpleType>
</xs:schema>

=== L2jOrg/L2jOrg/Datapack/gameserver/data/items/15500-15599.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://l2j.org" xsi:schemaLocation="http://l2j.org items.xsd">
	<armor id="15592" name="Vorpal Breastplate" type="LIGHT" body-part="CHEST" icon="icon.armor_t94_u_i03">
	<!-- Male Kamael Appearance -->
		<restriction freightable="false"/>
		<attributes weight="7520" price="7960" enchant-enabled="false" />
		<crystal />
		<stats>
			<stat type="PHYSICAL_DEFENCE" value="47.0"/>
		</stats>
	</armor>

	<armor id="15595" name="Vorpal Gaiters" type="LIGHT" body-part="LEGS" icon="icon.armor_t94_l_i03">
	<!-- Male Kamael Appearance -->
		<restriction freightable="false"/>
		<attributes weight="3170" price="12700" enchant-enabled="false" />
		<crystal />
		<stats>
			<stat type="PHYSICAL_DEFENCE" value="32.0"/>
		</stats>
	</armor>

	<armor id="15598" name="Vorpal Gauntlets" type="NONE" body-part="GLOVES" icon="icon.armor_t94_g_i03">
	<!-- Male Kamael Appearance -->
		<restriction freightable="false"/>
		<attributes weight="510" price="33300" />
		<crystal type="D"/>
		<stats>
			<stat type="PHYSICAL_DEFENCE" value="22.0"/>
		</stats>
	</armor>

</list>
