=== L2jOrg/L2jOrg/Datapack/gameserver/data/teleporters/teleporterData.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
		   targetNamespace="http://l2j.org"
		   xmlns="http://l2j.org"
		   elementFormDefault="qualified">

	<xs:include schemaLocation="../xsd/common.xsd"/>

	<xs:element name="list">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="npc" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="npcs" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="npc" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:attribute type="xs:int" name="id" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="teleport" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="location" type="TeleportLocation" maxOccurs="unbounded" minOccurs="0"/>
									</xs:sequence>
									<xs:attribute name="name" type="xs:string"/>
									<xs:attribute name="type" type="TeleportType">
									</xs:attribute>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute type="xs:integer" name="id" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:simpleType name="TeleportType">
		<xs:restriction base="xs:token">
			<xs:enumeration value="NORMAL" />
			<xs:enumeration value="HUNTING" />
			<xs:enumeration value="NOBLES_TOKEN" />
			<xs:enumeration value="NOBLES_ADENA" />
			<xs:enumeration value="OTHER" />
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="TeleportLocation">
		<xs:complexContent>
			<xs:extension base="Location">
				<xs:attribute type="xs:string" name="name" />
				<xs:attribute type="xs:int" name="npcStringId" default="-1" />
				<xs:attribute type="xs:int" name="questZoneId"  />
				<xs:attribute type="xs:int" name="feeId" />
				<xs:attribute type="xs:int" name="feeCount"  />
				<xs:attribute name="castleId">
					<xs:simpleType>
						<xs:restriction base="xs:token">
							<xs:pattern value="\d+(;\d+)*" />
						</xs:restriction>
					</xs:simpleType>
				</xs:attribute>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
</xs:schema>

=== L2jOrg/L2jOrg/Datapack/gameserver/data/teleporters/town/Clarissa.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/teleporterData.xsd">
	<npc id="30080"> <!-- Clarissa -->
		<teleport type="NORMAL">
			<!-- feeCount from retail classic -->
			<location npcStringId="1010006" x="15671" y="142994" z="-2696" feeCount="6800" /> <!-- Town of Dion -->
			<location npcStringId="1010013" x="83011" y="53207" z="-1488" feeCount="9400" /> <!-- Town of Oren -->
            <location npcStringId="1010020" x="117088" y="76931" z="-2696" feeCount="4100" /> <!-- Hunter's Village -->
			<location npcStringId="1001007" x="148024" y="-55281" z="-2728" feeCount="11100" /> <!-- Goddard -->
			<location npcStringId="1010023" x="146813" y="25807" z="-2008" feeCount="13000" /> <!-- Town of Aden -->
			<location npcStringId="1010022" x="105918" y="109759" z="-3192" feeCount="4400" /> <!-- Hardin's Academy -->
			<location npcStringId="1010021" x="47935" y="186810" z="-3480" feeCount="5200" /> <!-- Giran Harbor -->
			<location npcStringId="1010117" x="73024" y="118485" z="-3696" feeCount="870" /> <!-- Three-way crossroads at Dragon Valley -->
			<location npcStringId="1010518" x="115583" y="192261" z="-3488" feeCount="1500" /> <!-- Entrance to the Alligator Island -->
			<location npcStringId="1010504" x="43408" y="206881" z="-3752" feeCount="1900" /> <!-- Entrance to the Devil's Isle -->
			<location npcStringId="1010228" x="177347" y="173049" z="-1920" feeCount="15300" /> <!-- Land of Winds (Lv. 78) -->
			<location npcStringId="1010153" x="82098" y="252437" z="-10592" feeCount="15300" /> <!-- Garden of Eva (Lv. 78) -->
		</teleport>
	</npc>
</list>
