=== L2jOrg/L2jOrg/Datapack/gameserver/data/stats/npcs/npcs.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
		   targetNamespace="http://l2j.org"
		   xmlns="http://l2j.org"
		   elementFormDefault="qualified">

	<xs:include schemaLocation="../../xsd/common.xsd"/>

	<xs:element name="list">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="npc" maxOccurs="unbounded">
					<xs:complexType>
						<xs:all>
							<xs:element name="parameters" minOccurs="0">
								<xs:complexType>
									<xs:choice maxOccurs="unbounded">
										<xs:element name="param">
											<xs:complexType>
												<xs:attribute name="name" type="xs:token" use="required" />
												<xs:attribute name="value" type="xs:string" use="required" />
											</xs:complexType>
										</xs:element>
										<xs:element name="skill">
											<xs:complexType>
												<xs:attribute name="name" type="xs:token" use="required" />
												<xs:attribute name="id" type="xs:positiveInteger" use="required" />
												<xs:attribute name="level" type="xs:positiveInteger" use="required" />
											</xs:complexType>
										</xs:element>
										<xs:element name="minions">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="npc" maxOccurs="unbounded">
														<xs:complexType>
															<xs:attribute name="id" type="xs:positiveInteger" use="required" />
															<xs:attribute name="count" type="xs:positiveInteger" use="required" />
															<xs:attribute name="respawnTime" type="xs:nonNegativeInteger" use="required" />
															<xs:attribute name="weightPoint" type="xs:integer" use="required" />
														</xs:complexType>
													</xs:element>
												</xs:sequence>
												<xs:attribute name="name" type="xs:token" use="required" />
											</xs:complexType>
										</xs:element>
									</xs:choice>
								</xs:complexType>
							</xs:element>
							<xs:element name="race" type="xs:token" minOccurs="0"/>
							<xs:element name="sex" type="xs:token" minOccurs="0"/>
							<xs:element name="equipment" minOccurs="0">
								<xs:complexType>
									<xs:attribute name="chest" type="xs:nonNegativeInteger" />
									<xs:attribute name="rhand" type="xs:nonNegativeInteger" />
									<xs:attribute name="lhand" type="xs:nonNegativeInteger" />
									<xs:attribute name="weaponEnchant" type="xs:nonNegativeInteger" />
								</xs:complexType>
							</xs:element>
							<xs:element name="acquire" minOccurs="0">
								<xs:complexType>
									<xs:attribute name="exp" type="xs:decimal" />
									<xs:attribute name="sp" type="xs:decimal" />
									<xs:attribute name="raidPoints" type="xs:decimal" />
									<xs:attribute name="attribute_exp" type="xs:long" default="0"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="mpReward" minOccurs="0">
								<xs:complexType>
									<xs:attribute name="value" type="xs:positiveInteger" />
									<xs:attribute name="type">
										<xs:simpleType>
											<xs:restriction base="xs:token">
												<xs:enumeration value="DIFF" />
												<xs:enumeration value="PER" />
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="ticks" type="xs:positiveInteger" />
									<xs:attribute name="affects">
										<xs:simpleType>
											<xs:restriction base="xs:token">
												<xs:enumeration value="SOLO" />
												<xs:enumeration value="PARTY" />
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
								</xs:complexType>
							</xs:element>
							<xs:element name="stats" minOccurs="0">
								<xs:complexType>
									<xs:all>
										<xs:element name="vitals" minOccurs="0">
											<xs:complexType>
												<xs:attribute name="hp" type="xs:decimal" />
												<xs:attribute name="hpRegen" type="xs:decimal" />
												<xs:attribute name="mp" type="xs:decimal" />
												<xs:attribute name="mpRegen" type="xs:decimal" />
											</xs:complexType>
										</xs:element>
										<xs:element name="attack" minOccurs="0">
											<xs:complexType>
												<xs:attribute name="physical" type="xs:decimal" />
												<xs:attribute name="magical" type="xs:decimal" />
												<xs:attribute name="random" type="xs:nonNegativeInteger" />
												<xs:attribute name="critical" type="xs:decimal" />
												<xs:attribute name="accuracy" type="xs:float" />
												<xs:attribute name="attackSpeed" type="xs:float" />
												<xs:attribute name="reuseDelay" type="xs:nonNegativeInteger" />
												<xs:attribute name="type" type="xs:token" />
												<xs:attribute name="range" type="xs:nonNegativeInteger" />
												<xs:attribute name="distance" type="xs:nonNegativeInteger" />
												<xs:attribute name="width" type="xs:nonNegativeInteger" />
											</xs:complexType>
										</xs:element>
										<xs:element name="defence" minOccurs="0">
											<xs:complexType>
												<xs:attribute name="physical" type="xs:decimal" />
												<xs:attribute name="magical" type="xs:decimal" />
												<xs:attribute name="evasion" type="xs:integer" />
												<xs:attribute name="shield" type="xs:nonNegativeInteger" />
												<xs:attribute name="shieldRate" type="xs:nonNegativeInteger" />
											</xs:complexType>
										</xs:element>
										<xs:element name="abnormalResist" minOccurs="0">
											<xs:complexType>
												<xs:attribute name="physical" type="xs:decimal" />
												<xs:attribute name="magical" type="xs:decimal" />
											</xs:complexType>
										</xs:element>
										<xs:element name="attribute" minOccurs="0">
											<xs:complexType>
												<xs:all>
													<xs:element name="attack" minOccurs="0">
														<xs:complexType>
															<xs:attribute name="type" type="xs:token" />
															<xs:attribute name="value" type="xs:nonNegativeInteger" />
														</xs:complexType>
													</xs:element>
													<xs:element name="defence" minOccurs="0">
														<xs:complexType>
															<xs:attribute name="fire" type="xs:integer" />
															<xs:attribute name="water" type="xs:integer" />
															<xs:attribute name="wind" type="xs:integer" />
															<xs:attribute name="earth" type="xs:integer" />
															<xs:attribute name="holy" type="xs:integer" />
															<xs:attribute name="dark" type="xs:integer" />
															<xs:attribute name="default" type="xs:integer" />
														</xs:complexType>
													</xs:element>
												</xs:all>
											</xs:complexType>
										</xs:element>
										<xs:element name="speed" minOccurs="0">
											<xs:complexType>
												<xs:all>
													<xs:element name="walk" minOccurs="0">
														<xs:complexType>
															<xs:attribute name="ground" type="xs:decimal" />
															<xs:attribute name="swim" type="xs:decimal" />
															<xs:attribute name="fly" type="xs:decimal" />
														</xs:complexType>
													</xs:element>
													<xs:element name="run" minOccurs="0">
														<xs:complexType>
															<xs:attribute name="ground" type="xs:decimal" />
															<xs:attribute name="swim" type="xs:decimal" />
															<xs:attribute name="fly" type="xs:decimal" />
														</xs:complexType>
													</xs:element>
												</xs:all>
											</xs:complexType>
										</xs:element>
										<xs:element name="hitTime" type="xs:nonNegativeInteger" minOccurs="0"/>
									</xs:all>
									<xs:attribute name="str" type="xs:nonNegativeInteger" />
									<xs:attribute name="int" type="xs:nonNegativeInteger" />
									<xs:attribute name="dex" type="xs:nonNegativeInteger" />
									<xs:attribute name="wit" type="xs:nonNegativeInteger" />
									<xs:attribute name="con" type="xs:nonNegativeInteger" />
									<xs:attribute name="men" type="xs:nonNegativeInteger" />
								</xs:complexType>
							</xs:element>
							<xs:element name="status" minOccurs="0">
								<xs:complexType>
									<xs:attribute name="unique" type="xs:boolean" />
									<xs:attribute name="attackable" type="xs:boolean" />
									<xs:attribute name="talkable" type="xs:boolean" />
									<xs:attribute name="targetable" type="xs:boolean" />
									<xs:attribute name="undying" type="xs:boolean" />
									<xs:attribute name="showName" type="xs:boolean" />
									<xs:attribute name="randomWalk" type="xs:boolean" />
									<xs:attribute name="randomAnimation" type="xs:boolean" />
									<xs:attribute name="flying" type="xs:boolean" />
									<xs:attribute name="canMove" type="xs:boolean" />
									<xs:attribute name="noSleepMode" type="xs:boolean" />
									<xs:attribute name="passableDoor" type="xs:boolean" />
									<xs:attribute name="hasSummoner" type="xs:boolean" />
									<xs:attribute name="canBeSown" type="xs:boolean" />
									<xs:attribute name="isDeathPenalty" type="xs:boolean" />
								</xs:complexType>
							</xs:element>
							<xs:element name="skillList" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="skill" maxOccurs="unbounded">
											<xs:complexType>
												<xs:attribute name="id" type="xs:nonNegativeInteger" use="required" />
												<xs:attribute name="level" type="xs:nonNegativeInteger" use="required" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="shots" minOccurs="0">
								<xs:complexType>
									<xs:attribute name="soul" type="xs:nonNegativeInteger" />
									<xs:attribute name="spirit" type="xs:nonNegativeInteger" />
									<xs:attribute name="shotChance" type="xs:nonNegativeInteger" />
									<xs:attribute name="spiritChance" type="xs:nonNegativeInteger" />
								</xs:complexType>
							</xs:element>
							<xs:element name="corpseTime" type="xs:nonNegativeInteger" minOccurs="0"/>
							<xs:element name="exCrtEffect" type="xs:boolean" minOccurs="0"/>
							<xs:element name="sNpcPropHpRate" type="xs:decimal" minOccurs="0"/>
							<xs:element name="ai" minOccurs="0">
								<xs:complexType>
									<xs:all>
										<xs:element name="skill" minOccurs="0">
											<xs:complexType>
												<xs:attribute name="minChance" type="xs:nonNegativeInteger" />
												<xs:attribute name="maxChance" type="xs:nonNegativeInteger" />
												<xs:attribute name="primaryId" type="xs:nonNegativeInteger" />
												<xs:attribute name="shortRangeId" type="xs:nonNegativeInteger" />
												<xs:attribute name="shortRangeChance" type="xs:nonNegativeInteger" />
												<xs:attribute name="longRangeId" type="xs:nonNegativeInteger" />
												<xs:attribute name="longRangeChance" type="xs:nonNegativeInteger" />
											</xs:complexType>
										</xs:element>
										<xs:element name="clanList" minOccurs="0">
											<xs:complexType>
												<xs:choice maxOccurs="unbounded">
													<xs:element name="clan" type="xs:token" />
													<xs:element name="ignoreNpcId" type="xs:nonNegativeInteger" />
												</xs:choice>
											</xs:complexType>
										</xs:element>
									</xs:all>
									<xs:attribute name="type" type="xs:token" />
									<xs:attribute name="aggroRange" type="xs:nonNegativeInteger" />
									<xs:attribute name="clanHelpRange" type="xs:nonNegativeInteger" />
									<xs:attribute name="dodge" type="xs:nonNegativeInteger" />
									<xs:attribute name="isChaos" type="xs:boolean" />
									<xs:attribute name="isAggressive" type="xs:boolean" />
								</xs:complexType>
							</xs:element>
							<xs:element name="dropLists" minOccurs="0">
								<xs:complexType>
									<xs:all>
										<xs:element name="drop" type="dropList" minOccurs="0"/>
										<xs:element name="spoil" type="dropList" minOccurs="0"/>
										<xs:element name="lucky" type="dropList" minOccurs="0"/>
									</xs:all>
								</xs:complexType>
							</xs:element>
							<xs:element name="collision" minOccurs="0">
								<xs:complexType>
									<xs:all>
										<xs:element name="radius" minOccurs="0">
											<xs:complexType>
												<xs:attribute name="normal" type="xs:decimal" />
												<xs:attribute name="grown" type="xs:decimal" />
											</xs:complexType>
										</xs:element>
										<xs:element name="height" minOccurs="0">
											<xs:complexType>
												<xs:attribute name="normal" type="xs:decimal" />
												<xs:attribute name="grown" type="xs:decimal" />
											</xs:complexType>
										</xs:element>
									</xs:all>
								</xs:complexType>
							</xs:element>
							<xs:element name="extendDrop" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element type="xs:byte" name="id" maxOccurs="unbounded"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:all>
						<xs:attribute name="id" type="xs:positiveInteger" use="required" />
						<xs:attribute name="displayId" type="xs:positiveInteger" />
						<xs:attribute name="level" type="xs:byte" />
						<xs:attribute name="type" type="xs:token" />
						<xs:attribute name="name" type="xs:string" />
						<xs:attribute name="usingServerSideName" type="xs:boolean" />
						<xs:attribute name="title" type="xs:string" />
						<xs:attribute name="usingServerSideTitle" type="xs:boolean" />
						<xs:attribute name="element" type="Element" default="NONE"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="dropList">
		<xs:choice maxOccurs="unbounded">
			<xs:element name="item" type="dropListItem" />
		</xs:choice>
	</xs:complexType>

	<xs:complexType name="dropListItem">
		<xs:attribute name="id" type="xs:positiveInteger" use="required" />
		<xs:attribute name="min" type="xs:nonNegativeInteger" />
		<xs:attribute name="max" type="xs:positiveInteger" />
		<xs:attribute name="chance" type="xs:decimal" />
	</xs:complexType>

</xs:schema>

=== L2jOrg/L2jOrg/Datapack/gameserver/data/stats/npcs/08500-08599.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://l2j.org" xsi:schemaLocation="http://l2j.org npcs.xsd">
	<npc id="8534" level="85" type="Folk" name="Performer Snow">
		<!-- AUTO GENERATED NPC TODO: FIX IT -->
		<race>ETC</race>
		<sex>FEMALE</sex>
		<stats str="88" int="79" dex="55" wit="78" con="82" men="78">
			<vitals hp="8446" hpRegen="10.5" mp="2355" mpRegen="3.6" />
			<speed>
				<walk ground="60" />
				<run ground="120" />
			</speed>
			<attack physical="1950.2231755595" magical="1331.5869440987" critical="4" attackSpeed="253" range="40" />
			<defence physical="405.85106382979" magical="297.0297029703" />
		</stats>
		<status attackable="false" />
		<collision>
			<radius normal="5" />
			<height normal="12" />
		</collision>
	</npc>
</list>

=== L2jOrg/L2jOrg/Datapack/gameserver/data/stats/npcs/custom/tvt_event.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://l2j.org" xsi:schemaLocation="http://l2j.org ../npcs.xsd">
    <npc id="70010" displayId="31226" name="Manager" usingServerSideName="true" title="TvT Event" usingServerSideTitle="true" type="Folk">
        <race>HUMAN</race>
        <sex>MALE</sex>
        <equipment rhand="7884"/> <!-- Infernal Master -->
        <stats>
            <vitals hp="2444.46819" hpRegen="7.5" mp="1345.8" mpRegen="2.7"/>
            <attack physical="688.86373" magical="470.40463" random="30" critical="4" accuracy="95" attackSpeed="253" type="SWORD" range="40" distance="80" width="120"/>
            <defence physical="295.91597" magical="216.53847"/>
            <speed>
                <walk ground="40"/>
                <run ground="120"/>
            </speed>
        </stats>
        <status attackable="false"/>
        <collision>
            <radius normal="8"/>
            <height normal="23"/>
        </collision>
    </npc>
</list>

=== L2jOrg/L2jOrg/Datapack/gameserver/data/stats/npcs/25500-25599.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://l2j.org" xsi:schemaLocation="http://l2j.org npcs.xsd">
    <npc id="25500" level="44" type="Monster" name="Alligator of Istary" title="Raid Fighter">
        <race>BEAST</race>
        <sex>MALE</sex>
        <stats str="40" int="41" dex="30" wit="20" con="43" men="10">
            <vitals hp="33571" hpRegen="35.16" mp="26409" mpRegen="9"/>
            <attack physical="258.908" magical="29.731" random="30" critical="4" accuracy="20" attackSpeed="253" type="SWORD" range="40" distance="80" width="120"/>
            <defence physical="693.8" magical="253.82"/>
            <speed>
                <walk ground="70"/>
                <run ground="190"/>
            </speed>
            <hitTime>410</hitTime>
            <abnormalResist physical="10" magical="10"/>
        </stats>
        <status undying="false"/>
        <skillList>
            <skill id="4045" level="1"/> <!-- Resist Full Magic Attack -->
            <skill id="4408" level="1"/> <!-- HP Increase (1x) -->
            <skill id="4409" level="1"/> <!-- MP Increase (1x) -->
            <skill id="4410" level="11"/> <!-- Average P. Atk. -->
            <skill id="4411" level="11"/> <!-- Average M. Atk. -->
            <skill id="4412" level="11"/> <!-- Average P. Def. -->
            <skill id="4413" level="11"/> <!-- Average M. Def. -->
            <skill id="4414" level="3"/> <!-- Light Armor Type -->
            <skill id="4415" level="3"/> <!-- One-handed Sword -->
            <skill id="4416" level="4"/> <!-- Animals -->
        </skillList>
        <exCrtEffect>true</exCrtEffect>
        <ai clanHelpRange="300"/>
        <collision>
            <radius normal="28"/>
            <height normal="11.5"/>
        </collision>
    </npc>
</list>
