=== L2jOrg/L2jOrg/Datapack/gameserver/data/xsd/items.xsd
<?xml version="1.1" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:complexType name="skillsType">
		<xs:sequence>
			<xs:element name="skill" type="skillType" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="unequipSkillsType">
		<xs:sequence>
			<xs:element name="skill" type="skillType" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="capsuledItemsType">
		<xs:sequence>
			<xs:element name="item" type="capsuledItemType" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="createItemsType">
		<xs:sequence>
			<xs:element name="item" type="createItemType" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="skillType">
		<xs:attribute name="id" type="xs:positiveInteger" use="required" />
		<xs:attribute name="level" type="xs:positiveInteger" use="required" />
		<xs:attribute name="type">
			<xs:simpleType>
				<xs:restriction base="xs:token">
					<xs:enumeration value="NORMAL" />
					<xs:enumeration value="ON_ENCHANT" />
					<xs:enumeration value="ON_EQUIP" />
					<xs:enumeration value="ON_UNEQUIP" />
					<xs:enumeration value="ON_CRITICAL_SKILL" />
					<xs:enumeration value="ON_MAGIC_SKILL" />
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="type_chance" type="xs:positiveInteger" />
		<xs:attribute name="type_value" type="xs:positiveInteger" />
	</xs:complexType>

	<xs:complexType name="capsuledItemType">
		<xs:attribute name="id" type="xs:positiveInteger" />
		<xs:attribute name="min" type="xs:positiveInteger" />
		<xs:attribute name="max" type="xs:positiveInteger" />
		<xs:attribute name="chance" type="xs:double" />
		<xs:attribute name="minEnchant" type="xs:positiveInteger" use="optional" />
		<xs:attribute name="maxEnchant" type="xs:positiveInteger" use="optional" />
	</xs:complexType>

	<xs:complexType name="createItemType">
		<xs:attribute name="id" type="xs:positiveInteger" />
		<xs:attribute name="count" type="xs:positiveInteger" />
		<xs:attribute name="chance" type="xs:double" />
	</xs:complexType>

	<xs:complexType name="setType">
		<xs:attribute name="name" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:token">
					<xs:enumeration value="displayId" />
					<xs:enumeration value="armor_type" />
					<xs:enumeration value="attack_range" />
					<xs:enumeration value="auto_destroy_time" />
					<xs:enumeration value="blessed" />
					<xs:enumeration value="bodypart" />
					<xs:enumeration value="capsuled_items" />
					<xs:enumeration value="change_weaponId" />
					<xs:enumeration value="crystal_count" />
					<xs:enumeration value="crystal_type" />
					<xs:enumeration value="damage_range" />
					<xs:enumeration value="default_action" />
					<xs:enumeration value="duration" />
					<xs:enumeration value="element_enabled" />
					<xs:enumeration value="enchant_enabled" />
					<xs:enumeration value="enchant4_skill" />
					<xs:enumeration value="enchanted" />
					<xs:enumeration value="equip_condition" />
					<xs:enumeration value="equip_reuse_delay" />
					<xs:enumeration value="ex_immediate_effect" />
					<xs:enumeration value="extractableCountMin" />
					<xs:enumeration value="extractableCountMax" />
					<xs:enumeration value="etcitem_type" />
					<xs:enumeration value="for_npc" />
					<xs:enumeration value="handler" />
					<xs:enumeration value="icon" />
					<xs:enumeration value="immediate_effect" />
					<xs:enumeration value="is_depositable" />
					<xs:enumeration value="is_destroyable" />
					<xs:enumeration value="is_dropable" />
					<xs:enumeration value="is_freightable" />
					<xs:enumeration value="is_magic_weapon" />
					<xs:enumeration value="is_oly_restricted" />
					<xs:enumeration value="is_coc_restricted" />
					<xs:enumeration value="isAppearanceable" />
					<xs:enumeration value="is_premium" />
					<xs:enumeration value="is_questitem" />
					<xs:enumeration value="is_sellable" />
					<xs:enumeration value="is_stackable" />
					<xs:enumeration value="is_tradable" />
					<xs:enumeration value="is_infinite" />
					<xs:enumeration value="is_commissionable" />
					<xs:enumeration value="is_mailable" />
					<xs:enumeration value="is_clan_depositable" />
					<xs:enumeration value="is_private_storeable" />
					<xs:enumeration value="isAttackWeapon" />
					<xs:enumeration value="isForceEquip" />
					<xs:enumeration value="item_skill" />
					<xs:enumeration value="allow_self_resurrection" />
					<xs:enumeration value="material" />
					<xs:enumeration value="mp_consume" />
					<xs:enumeration value="oncrit_chance" />
					<xs:enumeration value="oncrit_skill" />
					<xs:enumeration value="onmagic_chance" />
					<xs:enumeration value="onmagic_skill" />
					<xs:enumeration value="price" />
					<xs:enumeration value="random_damage" />
					<xs:enumeration value="recipe_id" />
					<xs:enumeration value="reduced_mp_consume" />
					<xs:enumeration value="reduced_soulshot" />
					<xs:enumeration value="reuse_delay" />
					<xs:enumeration value="shared_reuse_group" />
					<xs:enumeration value="soulshots" />
					<xs:enumeration value="spiritshots" />
					<xs:enumeration value="time" />
					<xs:enumeration value="unequip_skill" />
					<xs:enumeration value="use_condition" />
					<xs:enumeration value="useSkillDisTime" />
					<xs:enumeration value="useWeaponSkillsOnly" />
					<xs:enumeration value="weapon_type" />
					<xs:enumeration value="weight" />
					<xs:enumeration value="commissionItemType" />
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="val" type="xs:token" use="required" />
	</xs:complexType>
	<xs:complexType name="playerType">
		<xs:attribute name="castle">
			<xs:simpleType>
				<xs:restriction base="xs:integer">
					<xs:minInclusive value="-1" />
					<xs:maxInclusive value="9" />
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="isOnSide" use="optional">
			<xs:simpleType>
				<xs:restriction base="xs:token">
					<xs:enumeration value="NEUTRAL" />
					<xs:enumeration value="LIGHT" />
					<xs:enumeration value="DARK" />
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="isClanLeader" type="xs:boolean" />
		<xs:attribute name="clanHall" type="xs:normalizedString" />
		<xs:attribute name="class_id_restriction" type="xs:normalizedString" />
		<xs:attribute name="cloakStatus" type="xs:boolean" />
		<xs:attribute name="isHero" type="xs:boolean" />
		<xs:attribute name="isPvpFlagged" type="xs:boolean" />
		<xs:attribute name="insideZoneId" type="xs:normalizedString" />
		<xs:attribute name="level">
			<xs:simpleType>
				<xs:restriction base="xs:positiveInteger">
					<xs:minInclusive value="1" />
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="pledgeClass">
			<xs:simpleType>
				<xs:restriction base="xs:integer">
					<xs:minInclusive value="-1" />
					<xs:maxInclusive value="11" />
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="levelRange" type="xs:token" />
		<xs:attribute name="races" type="xs:token" />
		<xs:attribute name="sex" type="xs:byte" use="optional" />
		<xs:attribute name="fort" type="xs:integer" />
		<xs:attribute name="chaotic" type="xs:boolean" />
		<xs:attribute name="subclass" type="xs:boolean" />
		<xs:attribute name="SiegeZone" type="xs:positiveInteger" />
		<xs:attribute name="flyMounted" type="xs:boolean" />
		<xs:attribute name="instanceId" type="xs:normalizedString" />
		<xs:attribute name="categoryType" type="xs:normalizedString" />
		<xs:attribute name="pkCount" type="xs:int" />
		<xs:attribute name="vehicleMounted" type="xs:boolean" />
		<xs:attribute name="MinimumVitalityPoints" type="xs:int" />
	</xs:complexType>
	<xs:complexType name="andType">
		<xs:choice maxOccurs="unbounded" minOccurs="0">
			<xs:element name="using" type="usingType" />
			<xs:element name="player" type="playerType" />
			<xs:element name="target" type="targetType" />
			<xs:element name="not" type="notType" />
			<xs:element name="game" type="gameType" />
			<xs:element name="or" minOccurs="0" type="andType" />
		</xs:choice>
	</xs:complexType>
	<xs:complexType name="gameType">
		<xs:attribute type="xs:string" name="night" />
	</xs:complexType>
	<xs:complexType name="notType">
		<xs:sequence>
			<xs:element name="using" minOccurs="0" type="usingType" />
			<xs:element name="player" minOccurs="0" type="playerType" />
			<xs:element name="target" minOccurs="0" type="targetType" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="usingType">
		<xs:attribute type="xs:string" name="kind" use="optional" />
		<xs:attribute type="xs:string" name="slot" use="optional" />
		<xs:attribute type="xs:string" name="weaponChange" use="optional" />
	</xs:complexType>
	<xs:complexType name="targetType">
		<xs:attribute name="levelRange" type="xs:token" />
		<xs:attribute name="categoryType" type="xs:normalizedString" />
	</xs:complexType>
	<xs:complexType name="enchantType">
		<xs:attribute name="order" type="xs:byte" use="optional" />
		<xs:attribute name="stat" use="required" type="statType" />
		<xs:attribute name="val" type="xs:integer" fixed="0" use="required" />
	</xs:complexType>
	<xs:simpleType name="statType">
		<xs:restriction base="xs:token">
			<xs:enumeration value="mAtk" />
			<xs:enumeration value="mDef" />
			<xs:enumeration value="pAtk" />
			<xs:enumeration value="pDef" />
			<xs:enumeration value="sDef" />
			<xs:enumeration value="mAtk" />
			<xs:enumeration value="pAtkAngle" />
			<xs:enumeration value="pAtkRange" />
			<xs:enumeration value="pAtkSpd" />
			<xs:enumeration value="rCrit" />
			<xs:enumeration value="mCritRate" />
			<xs:enumeration value="rShld" />
			<xs:enumeration value="rEvas" />
			<xs:enumeration value="mEvas" />
			<xs:enumeration value="accCombat" />
			<xs:enumeration value="accMagic" />
			<xs:enumeration value="darkRes" />
			<xs:enumeration value="earthRes" />
			<xs:enumeration value="fireRes" />
			<xs:enumeration value="holyPower" />
			<xs:enumeration value="holyRes" />
			<xs:enumeration value="maxMp" />
			<xs:enumeration value="waterRes" />
			<xs:enumeration value="windRes" />
			<xs:enumeration value="magicSuccRes" />
			<xs:enumeration value="moveSpeed" />
			<xs:enumeration value="broochJewels" />
			<xs:enumeration value="inventoryLimit" />
			<xs:enumeration value="randomDamage" />
			<xs:enumeration value="firePower" />
			<xs:enumeration value="waterPower" />
			<xs:enumeration value="windPower" />
			<xs:enumeration value="earthPower" />
			<xs:enumeration value="holyPower" />
			<xs:enumeration value="darkPower" />
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="condType">
		<xs:choice maxOccurs="unbounded" minOccurs="0">
			<xs:element name="using" type="usingType" />
			<xs:element name="and" type="andType" />
			<xs:element name="not" type="notType" />
			<xs:element name="player" type="playerType" />
			<xs:element name="target" type="targetType" />
		</xs:choice>
		<xs:attribute type="xs:short" name="msgId" use="optional" />
		<xs:attribute type="xs:byte" name="addName" use="optional" />
		<xs:attribute type="xs:string" name="msg" use="optional" />
	</xs:complexType>
	<xs:complexType name="forType" mixed="true">
		<xs:choice maxOccurs="unbounded" minOccurs="0">
			<xs:element name="stat" maxOccurs="unbounded" minOccurs="0">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:string">
							<xs:attribute type="statType" name="type" use="required" />
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="enchant" maxOccurs="2" minOccurs="0" type="enchantType" />
		</xs:choice>
		<xs:attribute type="xs:string" name="name" use="optional" />
		<xs:attribute type="xs:byte" name="val" use="optional" />
	</xs:complexType>
	<xs:complexType name="itemType">
		<xs:sequence maxOccurs="1" minOccurs="1">
			<xs:element name="set" maxOccurs="unbounded" minOccurs="1" type="setType" />
			<xs:element name="unequip_skills" minOccurs="0" type="skillsType" />
			<xs:element name="capsuled_items" minOccurs="0" type="capsuledItemsType" />
			<xs:element name="createItems" minOccurs="0" type="createItemsType" />
			<xs:element name="cond" maxOccurs="2" minOccurs="0" type="condType" />
			<xs:element name="skills" minOccurs="0" type="skillsType" />
			<xs:element name="stats" maxOccurs="1" minOccurs="0" type="forType" />
		</xs:sequence>
		<xs:attribute name="id" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:positiveInteger">
					<xs:minInclusive value="1" />
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="name" type="xs:normalizedString" use="required" />
		<xs:attribute name="additionalName" type="xs:normalizedString" use="optional" />
		<xs:attribute name="type" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:token">
					<xs:enumeration value="Armor" />
					<xs:enumeration value="EtcItem" />
					<xs:enumeration value="Weapon" />
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="item" type="itemType" minOccurs="1" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== L2jOrg/L2jOrg/Datapack/gameserver/data/stats/items/06800-06899.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/items.xsd">
	<item id="6835" name="Circlet of Dion" type="Armor">
		<!-- Torchlight Circlet. Can be worn by the lord of Dion Castle and clan members but not by allies. Allows use of Residential Skills when equipped. Cannot be exchanged, dropped, or sold. Can be stored in a private warehouse. -->
		<set name="icon" val="icon.accessory_pledge_cap1_i02" />
		<set name="default_action" val="EQUIP" />
		<set name="bodypart" val="hair" />
		<set name="immediate_effect" val="true" />
		<set name="material" val="WOOD" />
		<set name="weight" val="10" />
		<set name="price" val="500000" />
		<set name="is_tradable" val="false" />
		<set name="is_dropable" val="false" />
		<set name="is_sellable" val="false" />
		<set name="is_clan_depositable" val="false" />
		<set name="is_mailable" val="false" />
		<set name="is_private_storeable" val="false" />
		<set name="enchant_enabled" val="7" />
		<set name="commissionItemType" val="HAIR_ACCESSORY" />

		<set name="equip_condition" val="{{ec_castle;1};{ec_castle_num;{2}}}" />
		<cond msgId="1518">
			<and>
				<player castle="2" />
				<player pledgeClass="2" />
				<!-- Heir -->
			</and>
		</cond>
		<skills>
			<skill id="3633" level="1" /> <!-- Residential Stun Immunity -->
		</skills>
	</item>
	<item id="6837" name="Circlet of Oren" type="Armor">
		<!-- Tower Circlet. Can be worn by the lord of Oren Castle and clan members but not by allies. Allows use of Residential Skills when equipped. Cannot be exchanged, dropped, or sold. Can be stored in a private warehouse. -->
		<set name="icon" val="icon.accessory_pledge_cap1_i04" />
		<set name="default_action" val="EQUIP" />
		<set name="bodypart" val="hair" />
		<set name="immediate_effect" val="true" />
		<set name="material" val="WOOD" />
		<set name="weight" val="10" />
		<set name="price" val="500000" />
		<set name="is_tradable" val="false" />
		<set name="is_dropable" val="false" />
		<set name="is_sellable" val="false" />
		<set name="is_clan_depositable" val="false" />
		<set name="is_mailable" val="false" />
		<set name="is_private_storeable" val="false" />
		<set name="enchant_enabled" val="7" />
		<set name="commissionItemType" val="HAIR_ACCESSORY" />

		<set name="equip_condition" val="{{ec_castle;1};{ec_castle_num;{4}}}" />
		<cond msgId="1518">
			<and>
				<player castle="4" />
				<player pledgeClass="2" />
				<!-- Heir -->
			</and>
		</cond>
		<skills>
			<skill id="3633" level="1" /> <!-- Residential Stun Immunity -->
		</skills>
	</item>
	<item id="6838" name="Circlet of Gludio" type="Armor">
		<!-- Three-Swords Circlet. Can be worn by the lord of Gludio Castle and clan members but not by allies. Allows use of Residential Skills when equipped. Cannot be exchanged, dropped, or sold. Can be stored in a private warehouse. -->
		<set name="icon" val="icon.accessory_pledge_cap1_i05" />
		<set name="default_action" val="EQUIP" />
		<set name="bodypart" val="hair" />
		<set name="immediate_effect" val="true" />
		<set name="material" val="WOOD" />
		<set name="weight" val="10" />
		<set name="price" val="500000" />
		<set name="is_tradable" val="false" />
		<set name="is_dropable" val="false" />
		<set name="is_sellable" val="false" />
		<set name="is_clan_depositable" val="false" />
		<set name="is_mailable" val="false" />
		<set name="is_private_storeable" val="false" />
		<set name="enchant_enabled" val="7" />
		<set name="commissionItemType" val="HAIR_ACCESSORY" />

		<set name="equip_condition" val="{{ec_castle;1};{ec_castle_num;{1}}}" />
		<cond msgId="1518">
			<and>
				<player castle="1" />
				<player pledgeClass="2" />
				<!-- Heir -->
			</and>
		</cond>
		<skills>
			<skill id="3633" level="1" /> <!-- Residential Stun Immunity -->
		</skills>
	</item>
	<item id="6839" name="Circlet of Giran" type="Armor">
		<!-- Cross Circlet. Can be worn by the lord of Giran Castle and clan members but not by allies. Allows use of Residential Skills when equipped. Cannot be exchanged, dropped, or sold. Can be stored in a private warehouse. -->
		<set name="icon" val="icon.accessory_pledge_cap1_i06" />
		<set name="default_action" val="EQUIP" />
		<set name="bodypart" val="hair" />
		<set name="immediate_effect" val="true" />
		<set name="material" val="WOOD" />
		<set name="weight" val="10" />
		<set name="price" val="500000" />
		<set name="is_tradable" val="false" />
		<set name="is_dropable" val="false" />
		<set name="is_sellable" val="false" />
		<set name="is_clan_depositable" val="false" />
		<set name="is_mailable" val="false" />
		<set name="is_private_storeable" val="false" />
		<set name="enchant_enabled" val="7" />
		<set name="commissionItemType" val="HAIR_ACCESSORY" />

		<set name="equip_condition" val="{{ec_castle;1};{ec_castle_num;{3}}}" />
		<cond msgId="1518">
			<and>
				<player castle="3" />
				<player pledgeClass="2" />
				<!-- Heir -->
			</and>
		</cond>
		<skills>
			<skill id="3633" level="1" /> <!-- Residential Stun Immunity -->
		</skills>
	</item>
	<item id="6840" name="Circlet of Adena" type="Armor">
		<!-- Lion Circlet. Can be worn by the lord of Town of Aden Castle and clan members but not by allies. Allows use of Residential Skills when equipped. Cannot be exchanged, dropped, or sold. Can be stored in a private warehouse. -->
		<set name="icon" val="icon.accessory_pledge_cap2_i07" />
		<set name="default_action" val="EQUIP" />
		<set name="bodypart" val="hair" />
		<set name="immediate_effect" val="true" />
		<set name="material" val="WOOD" />
		<set name="weight" val="10" />
		<set name="price" val="500000" />
		<set name="is_tradable" val="false" />
		<set name="is_dropable" val="false" />
		<set name="is_sellable" val="false" />
		<set name="is_clan_depositable" val="false" />
		<set name="is_mailable" val="false" />
		<set name="is_private_storeable" val="false" />
		<set name="enchant_enabled" val="7" />
		<set name="commissionItemType" val="HAIR_ACCESSORY" />

		<set name="equip_condition" val="{{ec_castle;1};{ec_castle_num;{5}}}" />
		<cond msgId="1518">
			<and>
				<player castle="5" />
				<player pledgeClass="2" />
				<!-- Heir -->
			</and>
		</cond>
		<skills>
			<skill id="3633" level="2" /> <!-- Residential Stun Immunity -->
		</skills>
	</item>
	<item id="6841" name="Lord's Crown" type="Armor">
		<!-- Hair Accessory, Lord's Crown. Cannot be exchanged, dropped, or sold. Can be stored in a private warehouse. -->
		<set name="icon" val="icon.accessory_crown_i00" />
		<set name="default_action" val="EQUIP" />
		<set name="bodypart" val="hair" />
		<set name="immediate_effect" val="true" />
		<set name="material" val="WOOD" />
		<set name="weight" val="10" />
		<set name="is_tradable" val="false" />
		<set name="is_dropable" val="false" />
		<set name="is_sellable" val="false" />
		<set name="is_clan_depositable" val="false" />
		<set name="is_mailable" val="false" />
		<set name="is_private_storeable" val="false" />
		<set name="enchant_enabled" val="7" />
		<set name="commissionItemType" val="HAIR_ACCESSORY" />

		<set name="equip_condition" val="{{ec_castle;1};{ec_clan_leader;1}}" />
		<cond msgId="1518">
			<and>
				<player castle="-1" />
				<player pledgeClass="-1" />
				<!-- Clan Leader -->
			</and>
		</cond>
		<skills>
			<skill id="3632" level="1" /> <!-- Clan Gate -->
		</skills>
	</item>
	<item id="6842" name="Wings of Destiny Circlet" type="Armor">
		<!-- Hair Accessory, only for Heroes. Cannot be exchanged, dropped, or sold. Can be stored in a private warehouse. -->
		<set name="icon" val="icon.accessory_hero_cap_i00" />
		<set name="default_action" val="EQUIP" />
		<set name="bodypart" val="hair" />
		<set name="immediate_effect" val="true" />
		<set name="material" val="WOOD" />
		<set name="weight" val="10" />
		<set name="is_tradable" val="false" />
		<set name="is_dropable" val="false" />
		<set name="is_clan_depositable" val="false" />
		<set name="is_mailable" val="false" />
		<set name="is_private_storeable" val="false" />
		<set name="enchant_enabled" val="7" />
		<set name="commissionItemType" val="HAIR_ACCESSORY" />

		<set name="is_sellable" val="false" />
		<cond msgId="1518">
			<player isHero="true" />
		</cond>
	</item>
	<item id="6843" name="Cat Ears" type="Armor">
		<!-- Cat-ear shaped hair accessory. Occupies 1 Hair Accessory slot. Cannot be exchanged, dropped, or sold in a private store. Can be stored in a private warehouse. -->
		<set name="icon" val="icon.accessory_cat_ear_i00" />
		<set name="default_action" val="EQUIP" />
		<set name="bodypart" val="hair2" />
		<set name="immediate_effect" val="true" />
		<set name="material" val="WOOD" />
		<set name="weight" val="10" />
		<set name="price" val="500000" />
		<set name="enchant_enabled" val="7" />

		<set name="commissionItemType" val="HAIR_ACCESSORY" />
	</item>
	<item id="6845" name="Pirate's Eyepatch" type="Armor">
		<!-- Eyepatch accessory. Can teleport to the Entrance to the Devil's Isle. Cooldown: 2 hours. Cannot be exchanged, dropped, or sold. Can be stored in a private warehouse. -->
		<set name="icon" val="icon.accessory_eye_bandage_i00" />
		<set name="default_action" val="EQUIP" />
		<set name="bodypart" val="hair" />
		<set name="immediate_effect" val="true" />
		<set name="material" val="WOOD" />
		<set name="weight" val="10" />
		<set name="price" val="500000" />
		<set name="is_tradable" val="false" />
		<set name="is_dropable" val="false" />
		<set name="is_depositable" val="false" />
		<set name="is_sellable" val="false" />
	</item>
</list>

=== L2jOrg/L2jOrg/Datapack/gameserver/data/items/07900-07999.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://l2j.org" xsi:schemaLocation="http://l2j.org items.xsd">
    <weapon id="7900" name="Ice Storm Hammer" icon="icon.weapon_ice_storm_hammer_i00">
        <!-- Can bestow 1 regular Soul Crystal and 1 Special Soul Crystal. -->
        <set name="weapon_type" val="BLUNT"/>
        <set name="bodypart" val="lrhand"/>
        <set name="damage_range" val="0;0;44;120"/>
        <set name="immediate_effect" val="true"/>
        <set name="crystal_count" val="1157"/>
        <set name="crystal_type" val="B"/>
        <set name="weight" val="1950"/>
        <set name="price" val="8680000"/>
        <set name="soulshots" val="1"/>
        <set name="spiritshots" val="1"/>
        <set name="enchant_enabled" val="1"/>
        <set name="commissionItemType" val="TWO_HAND_BLUNT_WEAPON"/>
        <stats>
            <stat type="pAtk">213</stat>
            <stat type="mAtk">91</stat>
            <stat type="rCrit">6</stat>
            <stat type="accCombat">8</stat>
            <stat type="pAtkSpd">325</stat>
            <stat type="randomDamage">20</stat>
            <stat type="pAtkRange">40</stat>
        </stats>
    </weapon>
    <weapon id="7901" name="Star Buster" icon="icon.weapon_star_buster_i00">
        <!-- Can bestow 1 regular Soul Crystal and 1 Special Soul Crystal. -->
        <set name="weapon_type" val="BLUNT"/>
        <set name="bodypart" val="lrhand"/>
        <set name="damage_range" val="0;0;44;120"/>
        <set name="immediate_effect" val="true"/>
        <set name="crystal_count" val="1746"/>
        <set name="crystal_type" val="B"/>
        <set name="weight" val="1930"/>
        <set name="price" val="13100000"/>
        <set name="soulshots" val="1"/>
        <set name="spiritshots" val="1"/>
        <set name="enchant_enabled" val="1"/>
        <set name="commissionItemType" val="TWO_HAND_BLUNT_WEAPON"/>
        <stats>
            <stat type="pAtk">236</stat>
            <stat type="mAtk">99</stat>
            <stat type="rCrit">6</stat>
            <stat type="accCombat">8</stat>
            <stat type="pAtkSpd">325</stat>
            <stat type="randomDamage">20</stat>
            <stat type="pAtkRange">40</stat>
        </stats>
    </weapon>
    <weapon id="7902" name="Doom Crusher" icon="icon.weapon_doom_crusher_i00">
        <!-- Can bestow 1 regular Soul Crystal and 1 Special Soul Crystal. -->
        <set name="weapon_type" val="BLUNT"/>
        <set name="bodypart" val="lrhand"/>
        <set name="damage_range" val="0;0;44;120"/>
        <set name="immediate_effect" val="true"/>
        <set name="crystal_count" val="1659"/>
        <set name="crystal_type" val="A"/>
        <set name="weight" val="1900"/>
        <set name="price" val="20741000"/>
        <set name="soulshots" val="1"/>
        <set name="spiritshots" val="1"/>
        <set name="commissionItemType" val="TWO_HAND_BLUNT_WEAPON"/>
        <set name="enchant_enabled" val="1"/>
        <stats>
            <stat type="pAtk">282</stat>
            <stat type="mAtk">114</stat>
            <stat type="rCrit">6</stat>
            <stat type="accCombat">8</stat>
            <stat type="pAtkSpd">325</stat>
            <stat type="randomDamage">20</stat>
            <stat type="pAtkRange">40</stat>
        </stats>
    </weapon>
</list>

=== L2jOrg/L2jOrg/Datapack/gameserver/data/stats/items/47800-47899.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/items.xsd">
	<item id="47826" name="Hanbok" type="Armor">
		<!-- Items to make a Hanbok Outfit. -->
		<set name="icon" val="icon.ev_kr_traditional_dress" />
		<set name="default_action" val="EQUIP" />
		<set name="armor_type" val="HEAVY" />
		<set name="bodypart" val="alldress" />
		<set name="immediate_effect" val="true" />
		<set name="material" val="BRONZE" />
		<set name="is_tradable" val="false" />
		<set name="is_dropable" val="false" />
		<set name="is_destroyable" val="false" />
		<set name="is_depositable" val="false" />
		<set name="is_sellable" val="false" />
		<set name="is_freightable" val="true" />
	</item>
</list>

=== L2jOrg/L2jOrg/dist/game/data/stats/items/22200-22299.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/items.xsd">
	<item id="22223" name="Solid Scroll: Enchant Weapon (A-grade)" type="EtcItem">
		<!-- When enchanted, P. Atk. +4 for A-grade one-handed swords, one-handed blunts, daggers, spears, and other weapons. P. Atk. +5 for two-handed swords, two-handed blunts, dualswords, and two-handed fist weapons. P. Atk. +8 for bows. M. Atk. +3 for all weapons. Starting at +4, P. Atk. / M. Atk. bonus double. Safe Enchant: +3. -->
		<set name="icon" val="icon.giant_scrl_of_ench_wp_a" />
		<set name="default_action" val="SKILL_REDUCE" />
		<set name="material" val="PAPER" />
		<set name="is_stackable" val="true" />
	</item>
	<item id="22224" name="Solid Scroll: Enchant Armor (A-grade)" type="EtcItem">
		<!-- P. Def. +1 for A-grade armor and accessories. Starting from +4, P. Def. +3. If an armor is enchanted up to more than +4, HP is increased proportionally. Safe enchantment. If enchantment is failed, the item is not broken into crystals and preserves the enchantment level. Cannot be applied to armor enchanted by 7 and higher. -->
		<set name="icon" val="icon.giant_scrl_of_ench_am_a" />
		<set name="default_action" val="SKILL_REDUCE" />
		<set name="material" val="PAPER" />
		<set name="is_stackable" val="true" />
	</item>
</list>
