=== L2jOrg/L2jOrg/Datapack/gameserver/data/xsd/PetData.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="pets">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="pet" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="set" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="name" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:token">
												<xs:enumeration value="evolve" />
												<xs:enumeration value="food" />
												<xs:enumeration value="hungry_limit" />
												<xs:enumeration value="load" />
												<xs:enumeration value="sync_level" />
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="val" type="xs:token" use="required" />
								</xs:complexType>
							</xs:element>
							<xs:element name="skills" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="skill" maxOccurs="unbounded">
											<xs:complexType>
												<xs:attribute name="minLvl" type="xs:positiveInteger" use="required" />
												<xs:attribute name="skillId" type="xs:positiveInteger" use="required" />
												<xs:attribute name="skillLvl" type="xs:integer" use="required" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="stats">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="stat" maxOccurs="100">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="set" maxOccurs="unbounded">
														<xs:complexType>
															<xs:attribute name="name" use="required">
																<xs:simpleType>
																	<xs:restriction base="xs:token">
																		<xs:enumeration value="attack_speed_on_ride" />
																		<xs:enumeration value="consume_meal_in_battle" />
																		<xs:enumeration value="consume_meal_in_battle_on_ride" />
																		<xs:enumeration value="consume_meal_in_normal" />
																		<xs:enumeration value="consume_meal_in_normal_on_ride" />
																		<xs:enumeration value="exp" />
																		<xs:enumeration value="get_exp_type" />
																		<xs:enumeration value="mattack_on_ride" />
																		<xs:enumeration value="max_hp_on_ride" />
																		<xs:enumeration value="max_mp_on_ride" />
																		<xs:enumeration value="max_meal" />
																		<xs:enumeration value="org_hp" />
																		<xs:enumeration value="org_hp_regen" />
																		<xs:enumeration value="org_mattack" />
																		<xs:enumeration value="org_mdefend" />
																		<xs:enumeration value="org_mp" />
																		<xs:enumeration value="org_mp_regen" />
																		<xs:enumeration value="org_pattack" />
																		<xs:enumeration value="org_pdefend" />
																		<xs:enumeration value="pattack_on_ride" />
																		<xs:enumeration value="soulshot_count" />
																		<xs:enumeration value="speed_on_ride" />
																		<xs:enumeration value="spiritshot_count" />
																	</xs:restriction>
																</xs:simpleType>
															</xs:attribute>
															<xs:attribute name="val" type="xs:token" use="required" />
															<xs:attribute name="walk" type="xs:positiveInteger" />
															<xs:attribute name="run" type="xs:positiveInteger" />
															<xs:attribute name="slowSwim" type="xs:positiveInteger" />
															<xs:attribute name="fastSwim" type="xs:positiveInteger" />
															<xs:attribute name="slowFly" type="xs:positiveInteger" />
															<xs:attribute name="fastFly" type="xs:positiveInteger" />
														</xs:complexType>
													</xs:element>
												</xs:sequence>
												<xs:attribute name="level" type="xs:positiveInteger" use="required" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="id" type="xs:positiveInteger" use="required" />
						<xs:attribute name="itemId" type="xs:integer" use="required" />
						<xs:attribute name="index" type="xs:positiveInteger" use="required" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== L2jOrg/L2jOrg/Datapack/gameserver/data/stats/pets/[12527] Star Strider.xml
<?xml version="1.0" encoding="UTF-8"?>
<pets xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/PetData.xsd">
    <!-- star_strider -->
    <pet id="12527" itemId="4423" index="6">
        <set name="food" val="5169;5168;6316"/>
        <set name="hungry_limit" val="55"/>
        <set name="load" val="54510"/>
        <skills>
            <skill minLvl="1" skillId="4712" skillLvl="0"/>
            <skill minLvl="1" skillId="4713" skillLvl="0"/>
        </skills>
        <stats>
            <stat level="1">
                <set name="exp" val="0"/>
                <set name="get_exp_type" val="80"/>
                <set name="consume_meal_in_battle" val="3"/>
                <set name="consume_meal_in_normal" val="2"/>
                <set name="max_meal" val="696"/>
                <set name="soulshot_count" val="1"/>
                <set name="spiritshot_count" val="1"/>
                <set name="org_hp" val="19.872595"/>
                <set name="org_mp" val="40"/>
                <set name="org_pdefend" val="44.44444"/>
                <set name="org_mdefend" val="32.52252"/>
                <set name="org_pattack" val="1"/>
                <set name="org_mattack" val="2.7729552"/>
                <set name="org_hp_regen" val="2"/>
                <set name="org_mp_regen" val="0.9"/>
                <set name="speed_on_ride" val="0" walk="130" run="130" slowSwim="70" fastSwim="70"/>
            </stat>
            <stat level="2">
                <set name="exp" val="7"/>
                <set name="get_exp_type" val="80"/>
                <set name="consume_meal_in_battle" val="3"/>
                <set name="consume_meal_in_normal" val="2"/>
                <set name="max_meal" val="676"/>
                <set name="soulshot_count" val="1"/>
                <set name="spiritshot_count" val="1"/>
                <set name="org_hp" val="24.04584"/>
                <set name="org_mp" val="47.28"/>
                <set name="org_pdefend" val="46.15385"/>
                <set name="org_mdefend" val="33.77338"/>
                <set name="org_pattack" val="1"/>
                <set name="org_mattack" val="3.0502508"/>
                <set name="org_hp_regen" val="2"/>
                <set name="org_mp_regen" val="0.9"/>
                <set name="speed_on_ride" val="0" walk="130" run="130" slowSwim="70" fastSwim="70"/>
            </stat>
            <stat level="3">
                <set name="exp" val="42"/>
                <set name="get_exp_type" val="80"/>
                <set name="consume_meal_in_battle" val="4"/>
                <set name="consume_meal_in_normal" val="2"/>
                <set name="max_meal" val="892"/>
                <set name="soulshot_count" val="1"/>
                <set name="spiritshot_count" val="1"/>
                <set name="org_hp" val="28.77437"/>
                <set name="org_mp" val="54.64"/>
                <set name="org_pdefend" val="47.91652"/>
                <set name="org_mdefend" val="35.06323"/>
                <set name="org_pattack" val="1"/>
                <set name="org_mattack" val="3.3522256"/>
                <set name="org_hp_regen" val="2"/>
                <set name="org_mp_regen" val="0.9"/>
                <set name="speed_on_ride" val="0" walk="130" run="130" slowSwim="70" fastSwim="70"/>
            </stat>
            <stat level="4">
                <set name="exp" val="140"/>
                <set name="get_exp_type" val="80"/>
                <set name="consume_meal_in_battle" val="6"/>
                <set name="consume_meal_in_normal" val="2"/>
                <set name="max_meal" val="1112"/>
                <set name="soulshot_count" val="1"/>
                <set name="spiritshot_count" val="1"/>
                <set name="org_hp" val="34.104925"/>
                <set name="org_mp" val="62.08"/>
                <set name="org_pdefend" val="49.73343"/>
                <set name="org_mdefend" val="36.39277"/>
                <set name="org_pattack" val="1"/>
                <set name="org_mattack" val="3.6807437"/>
                <set name="org_hp_regen" val="2"/>
                <set name="org_mp_regen" val="0.9"/>
                <set name="speed_on_ride" val="0" walk="130" run="130" slowSwim="70" fastSwim="70"/>
            </stat>
            <stat level="5">
                <set name="exp" val="357"/>
                <set name="get_exp_type" val="80"/>
                <set name="consume_meal_in_battle" val="7"/>
                <set name="consume_meal_in_normal" val="2"/>
                <set name="max_meal" val="1428"/>
                <set name="soulshot_count" val="1"/>
                <set name="spiritshot_count" val="1"/>
                <set name="org_hp" val="40.086595"/>
                <set name="org_mp" val="69.6"/>
                <set name="org_pdefend" val="51.60553"/>
                <set name="org_mdefend" val="37.76269"/>
                <set name="org_pattack" val="1"/>
                <set name="org_mattack" val="4.0377758"/>
                <set name="org_hp_regen" val="2"/>
                <set name="org_mp_regen" val="0.9"/>
                <set name="speed_on_ride" val="0" walk="130" run="130" slowSwim="70" fastSwim="70"/>
            </stat>
            <stat level="6">
                <set name="exp" val="769"/>
                <set name="get_exp_type" val="80"/>
                <set name="consume_meal_in_battle" val="9"/>
                <set name="consume_meal_in_normal" val="2"/>
                <set name="max_meal" val="1740"/>
                <set name="soulshot_count" val="1"/>
                <set name="spiritshot_count" val="1"/>
                <set name="org_hp" val="46.77079"/>
                <set name="org_mp" val="77.2"/>
                <set name="org_pdefend" val="53.53373"/>
                <set name="org_mdefend" val="39.17366"/>
                <set name="org_pattack" val="1"/>
                <set name="org_mattack" val="4.4254023"/>
                <set name="org_hp_regen" val="2"/>
                <set name="org_mp_regen" val="0.9"/>
                <set name="speed_on_ride" val="0" walk="130" run="130" slowSwim="70" fastSwim="70"/>
            </stat>
            <stat level="7">
                <set name="exp" val="1481"/>
                <set name="get_exp_type" val="80"/>
                <set name="consume_meal_in_battle" val="10"/>
                <set name="consume_meal_in_normal" val="2"/>
                <set name="max_meal" val="1944"/>
                <set name="soulshot_count" val="1"/>
                <set name="spiritshot_count" val="1"/>
                <set name="org_hp" val="54.21127"/>
                <set name="org_mp" val="84.88"/>
                <set name="org_pdefend" val="55.51894"/>
                <set name="org_mdefend" val="40.62635"/>
                <set name="org_pattack" val="1"/>
                <set name="org_mattack" val="4.8458156"/>
                <set name="org_hp_regen" val="2"/>
                <set name="org_mp_regen" val="0.9"/>
                <set name="speed_on_ride" val="0" walk="130" run="130" slowSwim="70" fastSwim="70"/>
            </stat>
            <stat level="8">
                <set name="exp" val="2629"/>
                <set name="get_exp_type" val="80"/>
                <set name="consume_meal_in_battle" val="12"/>
                <set name="consume_meal_in_normal" val="2"/>
                <set name="max_meal" val="2228"/>
                <set name="soulshot_count" val="1"/>
                <set name="spiritshot_count" val="1"/>
                <set name="org_hp" val="62.46414"/>
                <set name="org_mp" val="92.64"/>
                <set name="org_pdefend" val="57.56203"/>
                <set name="org_mdefend" val="42.1214"/>
                <set name="org_pattack" val="1"/>
                <set name="org_mattack" val="5.3013222"/>
                <set name="org_hp_regen" val="2"/>
                <set name="org_mp_regen" val="0.9"/>
                <set name="speed_on_ride" val="0" walk="130" run="130" slowSwim="70" fastSwim="70"/>
            </stat>
            <stat level="9">
                <set name="exp" val="4388"/>
                <set name="get_exp_type" val="80"/>
                <set name="consume_meal_in_battle" val="12"/>
                <set name="consume_meal_in_normal" val="2"/>
                <set name="max_meal" val="2392"/>
                <set name="soulshot_count" val="1"/>
                <set name="spiritshot_count" val="1"/>
                <set name="org_hp" val="71.58782"/>
                <set name="org_mp" val="100.48"/>
                <set name="org_pdefend" val="59.66387"/>
                <set name="org_mdefend" val="43.65943"/>
                <set name="org_pattack" val="1"/>
                <set name="org_mattack" val="5.7943452"/>
                <set name="org_hp_regen" val="2"/>
                <set name="org_mp_regen" val="0.9"/>
                <set name="speed_on_ride" val="0" walk="130" run="130" slowSwim="70" fastSwim="70"/>
            </stat>
            <stat level="10">
                <set name="exp" val="6980"/>
                <set name="get_exp_type" val="80"/>
                <set name="consume_meal_in_battle" val="14"/>
                <set name="consume_meal_in_normal" val="2"/>
                <set name="max_meal" val="2584"/>
                <set name="soulshot_count" val="1"/>
                <set name="spiritshot_count" val="1"/>
                <set name="org_hp" val="81.643035"/>
                <set name="org_mp" val="108.4"/>
                <set name="org_pdefend" val="61.82527"/>
                <set name="org_mdefend" val="45.24105"/>
                <set name="org_pattack" val="1"/>
                <set name="org_mattack" val="6.3274249"/>
                <set name="org_hp_regen" val="2"/>
                <set name="org_mp_regen" val="0.9"/>
