=== L2jOrg/L2jOrg/Datapack/gameserver/data/xsd/transformations.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://l2j.org"
           xmlns="http://l2j.org"
           elementFormDefault="qualified">

    <xs:include schemaLocation="common.xsd"/>

    <xs:element name="list">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="transform">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Male" type="TransformationSex"/>
                            <xs:element name="Female" type="TransformationSex"/>
                        </xs:sequence>
                        <xs:attribute name="can_swim" use="required">
                            <xs:simpleType>
                                <xs:restriction base="xs:nonNegativeInteger">
                                    <xs:minInclusive value="0" />
                                    <xs:maxInclusive value="1" />
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                        <xs:attribute name="id" use="required">
                            <xs:simpleType>
                                <xs:restriction base="xs:positiveInteger">
                                    <xs:minInclusive value="1" />
                                    <xs:maxInclusive value="20019" />
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                        <xs:attribute name="displayId">
                            <xs:simpleType>
                                <xs:restriction base="xs:positiveInteger">
                                    <xs:minInclusive value="1" />
                                    <xs:maxInclusive value="20007" />
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                        <xs:attribute name="normal_attackable" use="required">
                            <xs:simpleType>
                                <xs:restriction base="xs:nonNegativeInteger">
                                    <xs:minInclusive value="0" />
                                    <xs:maxInclusive value="1" />
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                        <xs:attribute name="spawn_height" type="xs:positiveInteger" />
                        <xs:attribute name="type" use="required">
                            <xs:simpleType>
                                <xs:restriction base="xs:token">
                                    <xs:enumeration value="COMBAT" />
                                    <xs:enumeration value="CURSED" />
                                    <xs:enumeration value="FLYING" />
                                    <xs:enumeration value="MODE_CHANGE" />
                                    <xs:enumeration value="NON_COMBAT" />
                                    <xs:enumeration value="PURE_STAT" />
                                    <xs:enumeration value="RIDING_MODE" />
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                        <xs:attribute name="setName" type="xs:string"/>
                        <xs:attribute name="setTitle" type="xs:string"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>


    <xs:complexType name="TransformationSex">
        <xs:sequence>
            <xs:element name="common" minOccurs="0">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="base" minOccurs="0">
                            <xs:complexType>
                                <xs:attribute name="range" type="xs:positiveInteger" use="required" />
                                <xs:attribute name="attackSpeed" type="xs:positiveInteger" use="required" />
                                <xs:attribute name="attackType" use="required">
                                    <xs:simpleType>
                                        <xs:restriction base="xs:token">
                                            <xs:enumeration value="BOW" />
                                            <xs:enumeration value="DUAL" />
                                            <xs:enumeration value="SWORD" />
                                            <xs:enumeration value="FIST" />
                                        </xs:restriction>
                                    </xs:simpleType>
                                </xs:attribute>
                                <xs:attribute name="critRate" type="xs:positiveInteger" use="required" />
                                <xs:attribute name="mAtk" type="xs:positiveInteger" use="required" />
                                <xs:attribute name="pAtk" type="xs:positiveInteger" use="required" />
                                <xs:attribute name="randomDamage" type="xs:positiveInteger" use="required" />
                            </xs:complexType>
                        </xs:element>
                        <xs:element name="stats" minOccurs="0">
                            <xs:complexType>
                                <xs:attribute name="str" type="xs:positiveInteger" use="required" />
                                <xs:attribute name="int" type="xs:positiveInteger" use="required" />
                                <xs:attribute name="con" type="xs:positiveInteger" use="required" />
                                <xs:attribute name="dex" type="xs:positiveInteger" use="required" />
                                <xs:attribute name="wit" type="xs:positiveInteger" use="required" />
                                <xs:attribute name="men" type="xs:positiveInteger" use="required" />
                            </xs:complexType>
                        </xs:element>
                        <xs:element name="defense" minOccurs="0">
                            <xs:complexType>
                                <xs:attribute name="chest" type="xs:positiveInteger" use="required" />
                                <xs:attribute name="legs" type="xs:positiveInteger" use="required" />
                                <xs:attribute name="head" type="xs:positiveInteger" use="required" />
                                <xs:attribute name="feet" type="xs:positiveInteger" use="required" />
                                <xs:attribute name="gloves" type="xs:positiveInteger" use="required" />
                                <xs:attribute name="underwear" type="xs:positiveInteger" use="required" />
                                <xs:attribute name="cloak" type="xs:positiveInteger" use="required" />
                            </xs:complexType>
                        </xs:element>
                        <xs:element name="magicDefense" minOccurs="0">
                            <xs:complexType>
                                <xs:attribute name="rear" type="xs:positiveInteger" use="required" />
                                <xs:attribute name="lear" type="xs:positiveInteger" use="required" />
                                <xs:attribute name="rfinger" type="xs:positiveInteger" use="required" />
                                <xs:attribute name="lfinger" type="xs:positiveInteger" use="required" />
                                <xs:attribute name="neck" type="xs:positiveInteger" use="required" />
                            </xs:complexType>
                        </xs:element>
                        <xs:element name="collision">
                            <xs:complexType>
                                <xs:attribute name="radius" type="xs:decimal" use="required" />
                                <xs:attribute name="height" type="xs:decimal" use="required" />
                            </xs:complexType>
                        </xs:element>
                        <xs:element name="moving" minOccurs="0">
                            <xs:complexType>
                                <xs:attribute name="walk" type="xs:decimal" use="required" />
                                <xs:attribute name="run" type="xs:nonNegativeInteger" use="required" />
                                <xs:attribute name="waterWalk" type="xs:nonNegativeInteger" use="required" />
                                <xs:attribute name="waterRun" type="xs:nonNegativeInteger" use="required" />
                                <xs:attribute name="flyWalk" type="xs:nonNegativeInteger" use="required" />
                                <xs:attribute name="flyRun" type="xs:nonNegativeInteger" use="required" />
                                <xs:attribute name="unknownWalk" type="xs:nonNegativeInteger" use="required" />
                                <xs:attribute name="unknownRun" type="xs:nonNegativeInteger" use="required" />
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="actions" type="intList"/>
            <xs:element name="items" minOccurs="0">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="item" maxOccurs="unbounded">
                            <xs:complexType>
                                <xs:attribute name="id" use="required">
                                    <xs:simpleType>
                                        <xs:restriction base="xs:positiveInteger">
                                            <xs:minInclusive value="1" />
                                            <xs:maxInclusive value="65535" />
                                        </xs:restriction>
                                    </xs:simpleType>
                                </xs:attribute>
                                <xs:attribute name="allowed" use="required" type="xs:boolean" />
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="additionalSkills" minOccurs="0">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="skill" maxOccurs="unbounded">
                            <xs:complexType>
                                <xs:attribute name="id" use="required">
                                    <xs:simpleType>
                                        <xs:restriction base="xs:positiveInteger">
                                            <xs:minInclusive value="1" />
                                            <xs:maxInclusive value="65535" />
                                        </xs:restriction>
                                    </xs:simpleType>
                                </xs:attribute>
                                <xs:attribute name="level" use="required">
                                    <xs:simpleType>
                                        <xs:restriction base="xs:positiveInteger">
                                            <xs:minInclusive value="1" />
                                            <xs:maxInclusive value="99" />
                                        </xs:restriction>
                                    </xs:simpleType>
                                </xs:attribute>
                                <xs:attribute name="minLevel">
                                    <xs:simpleType>
                                        <xs:restriction base="xs:positiveInteger">
                                            <xs:minInclusive value="1" />
                                            <xs:maxInclusive value="99" />
                                        </xs:restriction>
                                    </xs:simpleType>
                                </xs:attribute>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="skills" minOccurs="0">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="skill" maxOccurs="unbounded">
                            <xs:complexType>
                                <xs:attribute name="id" use="required">
                                    <xs:simpleType>
                                        <xs:restriction base="xs:positiveInteger">
                                            <xs:minInclusive value="1" />
                                            <xs:maxInclusive value="65535" />
                                        </xs:restriction>
                                    </xs:simpleType>
                                </xs:attribute>
                                <xs:attribute name="level" use="required">
                                    <xs:simpleType>
                                        <xs:restriction base="xs:positiveInteger">
                                            <xs:minInclusive value="1" />
                                            <xs:maxInclusive value="99" />
                                        </xs:restriction>
                                    </xs:simpleType>
                                </xs:attribute>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="levels" minOccurs="0">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="level" maxOccurs="99">
                            <xs:complexType>
                                <xs:attribute name="levelMod" type="xs:decimal" use="required" />
                                <xs:attribute name="cpRegen" type="xs:decimal" use="required" />
                                <xs:attribute name="cp" type="xs:decimal" use="required" />
                                <xs:attribute name="hpRegen" type="xs:decimal" use="required" />
                                <xs:attribute name="hp" type="xs:decimal" use="required" />
                                <xs:attribute name="mpRegen" type="xs:decimal" use="required" />
                                <xs:attribute name="mp" type="xs:decimal" use="required" />
                                <xs:attribute name="val" use="required">
                                    <xs:simpleType>
                                        <xs:restriction base="xs:positiveInteger">
                                            <xs:minInclusive value="1" />
                                            <xs:maxInclusive value="99" />
                                        </xs:restriction>
                                    </xs:simpleType>
                                </xs:attribute>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== L2jOrg/L2jOrg/Datapack/gameserver/data/stats/transformations/164.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/transformations.xsd">
	<transform id="164" type="RIDING_MODE" can_swim="0" normal_attackable="0">
		<Male>
			<common>
				<base range="20" attackSpeed="300" attackType="SWORD" critRate="5" mAtk="5" pAtk="5" randomDamage="10" />
				<collision radius="21.5" height="19.7" />
				<moving walk="45" run="170" waterWalk="50" waterRun="50" flyWalk="0" flyRun="0" unknownWalk="0" unknownRun="0" />
			</common>
			<actions>1 3 4 5 6 7 8 9 11 15 16 17 18 19 21 22 23 32 36 39 40 41 42 43 44 45 46 47 48 50 52 53 54 55 56 57 63 64 65 70 86 1000 1001 1003 1004 1005 1006 1007 1008 1009 1010 1011 1012 1013 1014 1015 1016 1017 1018 1019 1020 1021 1022 1023 1024 1025 1026 1027 1028 1029 1030 1031 1032 1033 1034 1035 1036 1037 1038 1039 1040 1041 1042 1043 1044 1045 1046 1047 1048 1049 1050 1051 1052 1053 1054 1055 1056 1057 1058 1059 1060 1061 1062 1063 1064 1065 1066 1067 1068 1069 1070 1071 1072 1073 1074 1075 1076 1077 1078 1079 1080 1081 1082 1083 1084 1089 1090 1091 1092 1093 1094 1095 1096 1097 1098 1099 1100 1101 1102 1103 1104 1106 1107 1108 1109 1110 1111 1113 1114 1115 1116 1117 1118 1120 1121</actions>
			<skills>
				<skill id="9210" level="1" /> <!-- Dismount -->
				<skill id="5437" level="2" /> <!-- Dissonance -->
				<skill id="9206" level="1" /> <!-- Fast Run -->
			</skills>
		</Male>
		<Female>
			<common>
				<base range="20" attackSpeed="300" attackType="SWORD" critRate="5" mAtk="5" pAtk="5" randomDamage="10" />
				<collision radius="21.5" height="19.7" />
				<moving walk="45" run="170" waterWalk="50" waterRun="50" flyWalk="0" flyRun="0" unknownWalk="0" unknownRun="0" />
			</common>
			<actions>1 3 4 5 6 7 8 9 11 15 16 17 18 19 21 22 23 32 36 39 40 41 42 43 44 45 46 47 48 50 52 53 54 55 56 57 63 64 65 70 86 1000 1001 1003 1004 1005 1006 1007 1008 1009 1010 1011 1012 1013 1014 1015 1016 1017 1018 1019 1020 1021 1022 1023 1024 1025 1026 1027 1028 1029 1030 1031 1032 1033 1034 1035 1036 1037 1038 1039 1040 1041 1042 1043 1044 1045 1046 1047 1048 1049 1050 1051 1052 1053 1054 1055 1056 1057 1058 1059 1060 1061 1062 1063 1064 1065 1066 1067 1068 1069 1070 1071 1072 1073 1074 1075 1076 1077 1078 1079 1080 1081 1082 1083 1084 1089 1090 1091 1092 1093 1094 1095 1096 1097 1098 1099 1100 1101 1102 1103 1104 1106 1107 1108 1109 1110 1111 1113 1114 1115 1116 1117 1118 1120 1121</actions>
			<skills>
				<skill id="9210" level="1" /> <!-- Dismount -->
				<skill id="5437" level="2" /> <!-- Dissonance -->
				<skill id="9206" level="1" /> <!-- Fast Run -->
			</skills>
		</Female>
	</transform>
</list>
